# Generated by Django 5.0.3 on 2024-04-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dietary_restrictions',
            field=models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('VGN', 'Vegan'), ('GLF', 'Gluten-Free')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='max_cooking_time',
            field=models.IntegerField(blank=True, choices=[(5, '5 mins'), (10, '10 mins'), (15, '15 mins'), (20, '20 mins')], default=None, null=True),
        ),
    ]
