# Generated by Django 5.0.3 on 2024-04-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_dietary_restrictions_post_max_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dietary_restrictions',
        ),
    ]
